[project]
name = "spinnylight"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Wildbush", email = "75509166+Wildbush76@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "bleak>=3.0.2",
]

[project.scripts]
spinnylight = "spinnylight:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
